platform :ios, '13.0'

target 'Runner' do
  use_frameworks!

  # Firebase dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # Exclude arm64 for simulators
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
